### PR TITLE
CTCTRADERS-2244: Update plugins

### PR DESCRIPTION
**Pull request by ashwinirudrappa**

### CODE REVIEW

**Comment by ashwinirudrappa** [comment]
test this please

**Comment by ashwinirudrappa** [comment]
Test this please

**Comment by ashwinirudrappa** [comment]
Test

**Comment by ashwinirudrappa** [comment]
Test this please

**Comment by ashwinirudrappa** [comment]
Test this please

**Review by amaalali — APPROVED** [review]

**Pull request merged**
